version: '3.8'
services:
  ifuture-db:
    container_name: ifuture-db
    image: postgres:latest
    environment:
      POSTGRES_DB: "ifuture"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  server:
    container_name: server
    image: phoekoby/ifuture-server
    ports:
      - "8080:8080"

